---
dependencies:
  crypto: ^3.0.3
  freezed_annotation: ^3.1.0
  http: ^1.4.0
  json_annotation: ^4.9.0
description: Dart API wrapper for Bitbank.
dev_dependencies:
  auto_exporter: any
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  test: any
  very_good_analysis: any
environment:
  sdk: ^3.8.0
homepage: https://github.com/normidar/bitbank
name: bitbank
topics:
  - api
  - bitbank
  - blockchain
  - finance
  - exchange
version: 0.0.1
